package com.epam.jwd.controller;

public enum Action {
    SIGN_IN, SIGN_OUT, REGISTRATION, BUY_TICKET, CHECK_BALANCE, CHANGE_USER_NAME,
    CHANGE_USER_AGE, CHANGE_USER_EMAIL, CHECK_TICKET_PRICE, GET_AVAILABLE_TICKETS,
    GET_AVAILABLE_FOR_KIDS_TICKETS, GET_TICKETS_BY_MOVIE_NAME, GET_USERS_TICKETS;
}
